-- Drop existing table if it exists
DROP TABLE IF EXISTS sbir_data_new;

-- Create new table with exact CSV structure
CREATE TABLE sbir_data_new (
    id SERIAL PRIMARY KEY,
    "topic_number_api:_topiccode" TEXT,
    "topic_id_api:_topicid" TEXT,
    "title_api:_topictitle" TEXT,
    "short_title_derived:_first_50_chars_of_topictitle" TEXT,
    "component_api:_component" TEXT,
    "component_full_name_derived:_expanded_from_component_abbreviation" TEXT,
    "command_api:_command" TEXT,
    "program_api:_program" TEXT,
    "program_type_derived:_extracted_from_program_field" TEXT,
    "solicitation_api:_solicitationtitle" TEXT,
    "solicitation_number_api:_solicitationnumber" TEXT,
    "cycle_name_api:_cyclename" TEXT,
    "release_number_api:_releasenumber" TEXT,
    "solicitation_phase_derived:_extracted_from_cyclename_using_regex" TEXT,
    "status_api:_topicstatus" TEXT,
    "topic_status_api:_topicstatus_duplicate" TEXT,
    "proposal_window_status_calculated:_based_on_current_date_vs_start/end_dates" TEXT,
    "days_until_close_calculated:_topicenddate__current_date" TEXT,
    "days_since_open_calculated:_current_date__topicstartdate" TEXT,
    "urgency_level_calculated:_based_on_days_until_close_thresholds" TEXT,
    "open_date_api:_topicstartdate_converted_to_mm/dd/yyyy" TEXT,
    "close_date_api:_topicenddate_converted_to_mm/dd/yyyy" TEXT,
    "open_datetime_api:_topicstartdate_duplicate" TEXT,
    "close_datetime_api:_topicenddate_duplicate" TEXT,
    "duration_days_calculated:_topicenddate__topicstartdate" TEXT,
    "pre_release_start_api:_topicprereleasestartdate" TEXT,
    "pre_release_end_api:_topicprereleaseenddate" TEXT,
    "pre_release_duration_calculated:_prereleaseenddate__prereleasestartdate" TEXT,
    "created_date_api:_createddate" TEXT,
    "updated_date_api:_updateddate" TEXT,
    "modified_date_api:_modifieddate" TEXT,
    "last_activity_date_calculated:_max_of_updateddate,_modifieddate,_topicqaenddate" TEXT,
    "q&a_start_api:_topicqastartdate" TEXT,
    "q&a_end_api:_topicqaenddate" TEXT,
    "q&a_tpoc_start_api:_topicqatpocstartdate" TEXT,
    "q&a_tpoc_end_api:_topicqatpocenddate" TEXT,
    "q&a_status_api:_topicqastatus" TEXT,
    "q&a_status_display_api:_topicqastatusdisplay" TEXT,
    "q&a_open_api:_topicqaopen_boolean" TEXT,
    "q&a_window_active_calculated:_current_date_within_qa_start/end_range" TEXT,
    "days_until_q&a_close_calculated:_topicqaenddate__current_date" TEXT,
    "total_questions_api:_topicquestioncount" TEXT,
    "published_questions_api:_noofpublishedquestions" TEXT,
    "unpublished_questions_calculated:_topicquestioncount__noofpublishedquestions" TEXT,
    "q&a_response_rate_calculated:_publishedquestions/totalquestions_percentage" TEXT,
    "hasqa_derived:_1_if_topicquestioncount_>_0" TEXT,
    "qa_data_api:_topicquestioncount_duplicate" TEXT,
    "q&a_content_fetched:_from_/questions_endpoint_and_formatted" TEXT,
    "q&a_last_updated_extracted:_latest_answeredon_date_from_q&a_responses" TEXT,
    "technology_areas_api:_details.technologyareas_array_joined" TEXT,
    "technology_areas_count_calculated:_count_of_comma_separated_values" TEXT,
    "primary_technology_area_derived:_first_item_in_technologyareas" TEXT,
    "tech_modernization_api:_details.focusareas_mapped" TEXT,
    "modernization_priorities_api:_details.focusareas_array_joined" TEXT,
    "modernization_priority_count_calculated:_count_of_pipe_separated_values" TEXT,
    "keywords_api:_details.keywords" TEXT,
    "keywords_count_calculated:_count_of_semicolon_separated_values" TEXT,
    "primary_keyword_derived:_first_keyword_before_semicolon" TEXT,
    "itar_controlled_api:_details.itar_boolean_to_yes/no" TEXT,
    "requiresitar_derived:_1_if_itar_is_yes_else_0" TEXT,
    "security_export_api:_details.itar_duplicate" TEXT,
    "security_clearance_required_text_analysis:_keywords_in_description" TEXT,
    "objective_api:_details.objective_with_html_removed" TEXT,
    "objective_word_count_calculated:_space_separated_word_count" TEXT,
    "key_requirements_api:_details.objective_duplicate" TEXT,
    "description_api:_details.description_with_html_removed" TEXT,
    "description_word_count_calculated:_space_separated_word_count" TEXT,
    "description_length_calculated:_character_count" TEXT,
    "has_technical_details_derived:_1_if_description_>_500_chars" TEXT,
    "isxtech_text_analysis:_xtech_mentioned_in_description" TEXT,
    "is_xtech_text_analysis:_xtech_keyword_search_duplicate" TEXT,
    "prize_gating_derived:_yes_if_xtech_detected" TEXT,
    "competition_type_derived:_based_on_xtech_and_dp2_detection" TEXT,
    "phase_i_description_api:_details.phase1description_with_html_removed" TEXT,
    "phase_ii_description_api:_details.phase2description_with_html_removed" TEXT,
    "phase_iii_dual_use_api:_details.phase3description_with_html_removed" TEXT,
    "has_commercial_potential_derived:_1_if_phase3description_exists" TEXT,
    "references_api:_details.referencedocuments_array_formatted" TEXT,
    "reference_docs_api:_details.referencedocuments_duplicate" TEXT,
    "reference_count_calculated:_count_of_semicolon_separated_refs" TEXT,
    "has_references_derived:_1_if_references_exist" TEXT,
    "phase_api:_phasehierarchy_parsed_or_default_phase_i" TEXT,
    "phases_available_api:_phasehierarchy.config.displayvalue_joined" TEXT,
    "phase_types_api:_phasehierarchy_parsed_pipe_separated" TEXT,
    "phase_count_calculated:_count_of_phase_types" TEXT,
    "is_direct_to_phase_ii_text_analysis:_dp2_or_direct_to_phase_ii_in_text" TEXT,
    "phase_funding_text_extraction:_dollar_amounts_from_phase_descriptions" TEXT,
    "funding_max_text_extraction:_maximum_dollar_amount_found" TEXT,
    "award_amount_phase_i_text_extraction:_dollar_amount_from_phase1description" TEXT,
    "award_amount_phase_ii_text_extraction:_dollar_amount_from_phase2description" TEXT,
    "award_duration_phase_i_text_extraction:_months_from_phase1description" TEXT,
    "award_duration_phase_ii_text_extraction:_months_from_phase2description" TEXT,
    "total_potential_award_calculated:_sum_of_all_phase_amounts_found" TEXT,
    "funding_type_text_analysis:_cost_plus_or_fixed_price_keywords" TEXT,
    "topic_pdf_download_generated:_/topics/api/public/topics/{id}/download/pdf" TEXT,
    "pdf_link_generated:_topic_pdf_duplicate" TEXT,
    "solicitation_instructions_download_generated:_/submissions/api/public/download_url" TEXT,
    "solicitationinstructionsurl_generated:_solicitation_download_duplicate" TEXT,
    "component_instructions_download_generated:_component_specific_download_url" TEXT,
    "componentinstructionsurl_generated:_component_download_duplicate" TEXT,
    "has_pdf_derived:_1_if_pdf_link_exists" TEXT,
    "has_solicitation_instructions_derived:_1_if_solicitation_link_exists" TEXT,
    "has_component_instructions_derived:_1_if_component_link_exists" TEXT,
    "solicitation_instructions_version_api:_baaprefaceuploadtitle" TEXT,
    "component_instructions_version_api:_baainstructions_filename_match" TEXT,
    "tpoc_api:_topicmanagers_where_assignmenttype=tpoc_names_joined" TEXT,
    "tpoc_names_api:_topicmanagers.name_array" TEXT,
    "tpoc_emails_api:_topicmanagers.email_array" TEXT,
    "tpoc_centers_api:_topicmanagers.center_array" TEXT,
    "tpoc_count_calculated:_number_of_tpocs" TEXT,
    "has_tpoc_derived:_1_if_tpoc_exists" TEXT,
    "show_tpoc_api:_showtpoc_boolean" TEXT,
    "tpoc_email_domain_extracted:_domain_from_first_tpoc_email" TEXT,
    "owner_api:_owner_field" TEXT,
    "internal_lead_api:_internallead_field" TEXT,
    "sponsor_component_api:_sponsorcomponent_or_component_fallback" TEXT,
    "evaluation_weights_api:_evaluationweights_or_evaluationcriteria" TEXT,
    "selection_criteria_api:_selectioncriteria" TEXT,
    "has_evaluation_criteria_derived:_1_if_evaluation_weights_exist" TEXT,
    "historical_awards_api:_historicalawards" TEXT,
    "previous_awards_count_api:_previousawardscount" TEXT,
    "success_rate_api:_successrate" TEXT,
    "competition_level_estimated:_based_on_historicalawards_thresholds" TEXT,
    "year_system:_current_year" TEXT,
    "solicitation_year_extracted:_year_from_cyclename_using_regex" TEXT,
    "program_year_api:_programyear" TEXT,
    "fiscal_year_calculated:_based_on_oct_1_fiscal_year_start" TEXT,
    "quarter_calculated:_calendar_quarter_from_topicstartdate" TEXT,
    "baa_preface_upload_id_api:_baaprefaceuploadid" TEXT,
    "baa_preface_title_api:_baaprefaceuploadtitle" TEXT,
    "is_release_preface_api:_isreleasepreface_boolean" TEXT,
    "baa_instruction_files_api:_baainstructions.filename_array_joined" TEXT,
    "baa_files_count_calculated:_length_of_baainstructions_array" TEXT,
    "has_baa_instructions_derived:_1_if_baainstructions_exists" TEXT,
    "applicable_actions_api:_applicableactions_array_joined" TEXT,
    "actions_count_calculated:_length_of_applicableactions" TEXT,
    "is_active_api:_isactive_boolean" TEXT,
    "is_archived_api:_isarchived_boolean" TEXT,
    "is_draft_api:_isdraft_boolean" TEXT,
    "is_published_api:_ispublished_boolean" TEXT,
    "allow_proposal_submission_api:_allowproposalsubmission_boolean" TEXT,
    "is_open_for_submission_derived:_1_if_topicstatus_is_open" TEXT,
    "proposal_requirements_api:_proposalrequirements" TEXT,
    "submission_instructions_api:_submissioninstructions" TEXT,
    "eligibility_requirements_api:_eligibilityrequirements" TEXT,
    "has_special_requirements_text_analysis:_special_keywords_detected" TEXT,
    "information_quality_calculated:_based_on_key_field_lengths" TEXT,
    "data_completeness_score_calculated:_percentage_of_filled_fields" TEXT,
    "last_scraped_system:_current_timestamp_eastern" TEXT,
    "search_tags_generated:_component,_program,_status_combined" TEXT,
    "category_tags_text_analysis:_tech_categories_from_keywords" TEXT,
    "priority_score_calculated:_multi_factor_scoring_algorithm" TEXT,
    "relevance_score_user_defined:_empty_for_custom_scoring" TEXT,
    "record_id_generated:_topiccode_topicid_first_8_chars" TEXT,
    "unique_id_generated:_cyclename_topiccode" TEXT,
    "tracking_number_api:_trackingnumber_if_exists" TEXT,
    "version_api:_version_or_default_1" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for common queries
CREATE INDEX idx_sbir_new_topic_number ON sbir_data_new ("topic_number_api:_topiccode");
CREATE INDEX idx_sbir_new_topic_id ON sbir_data_new ("topic_id_api:_topicid");
CREATE INDEX idx_sbir_new_status ON sbir_data_new ("status_api:_topicstatus");
CREATE INDEX idx_sbir_new_component ON sbir_data_new ("component_api:_component");
CREATE INDEX idx_sbir_new_program ON sbir_data_new ("program_api:_program");
CREATE INDEX idx_sbir_new_open_date ON sbir_data_new ("open_date_api:_topicstartdate_converted_to_mm/dd/yyyy");
CREATE INDEX idx_sbir_new_close_date ON sbir_data_new ("close_date_api:_topicenddate_converted_to_mm/dd/yyyy");

-- Verify the table was created with all columns
SELECT COUNT(*) as total_columns 
FROM information_schema.columns 
WHERE table_name = 'sbir_data_new';
